# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: docker.io/mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ranadmin
      MONGO_INITDB_ROOT_PASSWORD: ranmal123

  mongo-express:
    image: docker.io/mongo-express
    restart: always
    ports:
      - 8123:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ranadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ranmal123
      ME_CONFIG_MONGODB_URL: mongodb://ranadmin:ranmal123@mongo:27017/
      ME_CONFIG_BASICAUTH: false
